wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1629794751
    t:
      1:
      - 1
      4: 3.8.8
      5: 0.12.0
      8:
      - 3
      - 5
alpha:
  desc: null
  value: 0.2
automatic_entropy_tuning:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
cuda:
  desc: null
  value: true
env_name:
  desc: null
  value: Trackmania
eval:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
hidden_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0003
num_steps:
  desc: null
  value: 1000001
policy:
  desc: null
  value: Gaussian
replay_size:
  desc: null
  value: 1000000
seed:
  desc: null
  value: 123456
start_steps:
  desc: null
  value: -1
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
updates_per_step:
  desc: null
  value: 1
